#!/bin/bash

ROOT=$(git rev-parse --show-toplevel)
echo "Downloading reference tests into $ROOT/eth-reference-tests/src/test/resources/"
bash <(curl -s https://raw.githubusercontent.com/PegaSysEng/artemis/master/scripts/get-ref-tests.sh)
